# Generated by Django 4.2.24 on 2026-03-27 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_alter_course_language"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="course",
            unique_together=set(),
        ),
    ]
